version: "3.9"

services: 

  poll:
    image: poll
    environment:
      HOST: redis
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    restart: on-failure

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure

  worker:
    image: worker
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - back-tier
    environment:
      REDIS: redis
      DB: db
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: postgres
    restart: on-failure

  db:
    image: postgres:9.4.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - back-tier
      - result-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

  result: 
    image: result
    environment:
      PORT_ENV: 80
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: postgres
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier
    restart: on-failure

volumes:
  db-data:

networks:
  poll-tier: 
  result-tier:
  back-tier: